# -*- coding: utf-8 -*-
"""Kopia notatnika mikołaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10KL45Ml9lzOJ0kocHQ9E7_Xii9ZUfUFg
"""

import streamlit as st
from svg_turtle import SvgTurtle
import random

# Tytuł aplikacji
st.title("🎅 Mikołaj rysowany w Pythonie")
st.caption("Generowanie obrazu wektorowego (SVG) przy użyciu logiki Turtle.")

# --- Funkcje pomocnicze (zmodyfikowane, aby przyjmowały obiekt 't') ---

def skok(t, x, y):
    """Przenosi żółwia bez rysowania"""
    t.penup()
    t.goto(x, y)
    t.pendown()

def rysuj_kolo(t, kolor, promien, x, y):
    """Rysuje wypełnione koło"""
    skok(t, x, y - promien)
    t.color(kolor)
    t.fillcolor(kolor)
    t.begin_fill()
    t.circle(promien)
    t.end_fill()

def rysuj_prostokat(t, kolor, w, h, x, y):
    """Rysuje prostokąt od lewego górnego rogu"""
    skok(t, x, y)
    t.color(kolor)
    t.fillcolor(kolor)
    t.begin_fill()
    for _ in range(2):
        t.forward(w)
        t.right(90)
        t.forward(h)
        t.right(90)
    t.end_fill()

def rysuj_tlo(t, szerokosc, wysokosc, kolor):
    """Rysuje tło jako duży prostokąt (svg_turtle ma domyślnie przezroczyste)"""
    skok(t, -szerokosc/2, wysokosc/2)
    t.color(kolor)
    t.fillcolor(kolor)
    t.begin_fill()
    for _ in range(2):
        t.forward(szerokosc)
        t.right(90)
        t.forward(wysokosc)
        t.right(90)
    t.end_fill()

# --- Główna logika rysowania ---
def generuj_obraz():
    # Inicjalizacja żółwia SVG (wymiary 600x600)
    t = SvgTurtle(600, 600)

    # 1. Rysowanie tła (niebo)
    rysuj_tlo(t, 600, 600, "#87CEEB")

    # 2. Podłoga (śnieg na ziemi)
    rysuj_prostokat(t, "white", 600, 150, -300, -150)

    # --- Rysowanie Mikołaja ---
    # Ciało (czerwone)
    rysuj_kolo(t, "red", 60, 0, -50)

    # Biały pasek na środku płaszcza
    rysuj_prostokat(t, "white", 10, 120, -5, 50)

    # Pasek (czarny)
    rysuj_prostokat(t, "black", 130, 10, -65, -50)
    # Klamra paska (żółta)
    rysuj_prostokat(t, "gold", 14, 14, -7, -48)

    # Głowa (cielista)
    rysuj_kolo(t, "#FFCC99", 30, 0, 60)

    # Oczy
    rysuj_kolo(t, "black", 3, -10, 75)
    rysuj_kolo(t, "black", 3, 10, 75)

    # Nos
    rysuj_kolo(t, "red", 4, 0, 65)

    # Broda
    locations = [(-25, 50), (-15, 45), (0, 40), (15, 45), (25, 50),
                 (-10, 35), (10, 35), (0, 30)]
    for lx, ly in locations:
        rysuj_kolo(t, "white", 8, lx, ly)

    # Czapka
    skok(t, -35, 85)
    t.color("red")
    t.fillcolor("red")
    t.begin_fill()
    t.goto(35, 85)
    t.goto(0, 140)
    t.goto(-35, 85)
    t.end_fill()

    # Białe futerko czapki
    rysuj_prostokat(t, "white", 80, 15, -40, 95)
    # Pompon
    rysuj_kolo(t, "white", 8, 0, 140)

    # --- Rysowanie Prezentów ---
    prezenty = [
        (-100, -160, "green", "gold"),
        (80, -160, "purple", "yellow"),
        (130, -170, "blue", "red")
    ]

    for px, py, p_kolor, w_kolor in prezenty:
        # Pudełko
        rysuj_prostokat(t, p_kolor, 40, 40, px, py)
        # Wstążka pionowa
        rysuj_prostokat(t, w_kolor, 8, 40, px + 16, py)
        # Wstążka pozioma
        rysuj_prostokat(t, w_kolor, 40, 8, px, py - 16)

    # --- Padający śnieg ---
    for _ in range(30):
        x = random.randint(-280, 280)
        y = random.randint(-280, 280)
        if y > -100:
            rysuj_kolo(t, "white", 2, x, y)

    # Zapisz wynik do pliku SVG
    filename = "mikolaj.svg"
    t.save_as(filename)
    return filename

# Przycisk do generowania (odświeża losowanie śniegu)
if st.button('Namaluj Mikołaja 🎨'):
    with st.spinner('Mikołaj się rysuje...'):
        plik_svg = generuj_obraz()
        st.image(plik_svg, width=600)
        st.success("Wesołych Świąt!")
else:
    st.info("Kliknij przycisk, aby wygenerować obrazek.")